country: china
province: beijing
city: beijing
area: haidian

port: 80

party: true

birthday: 1949-10-01

users1:
  name: itcast
  age: 16

user2:
  name: itheima
  age: 16


a:
  b:
    c:
      d:
        e: 123

likes:
  - game
  - music
  - sleep

likes2: [game,music,sleep]

users:
  - name: zhangsan
    age: 18
  - name: lisi
    age: 17

users3: [{name:zhangsan,age:18},{name:lisi,age:17}]

users2:
  -
    name: zhangsan
    age: 18
  -
    name: lisi
    age: 17

baseDir: c:/windows/user
# 如果需要转义,就需要加入双引号
# baseDir: "c:/windows/user"
currDir: ${baseDir}/tmp/


server:
  port: 80

datasource:
  driver: com.mysql.jdbc.Dirver
  url: jdbc:mysql://localhost/springboot_db
  username: root
  password: root123



